name: Lint

on: push

jobs:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v1

                  - name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@02a1172d274f021e4c70f66e23f1085eadd1064b
  uses: super-linter/super-linter@v7.0.0
          
        env:
          github_token: ${{ secrets.github_token }}
          
