name: Lint

on: push

jobs:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v1

      - name: Super-Linter
        uses: github/super-linter@v3.15.5
        env:
          github_token: ${{ secrets.github_token }}
          
